version: '2'
services:
  jobsampleapp-app:
    image: jobsampleapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jobsampleapp-postgresql:5432/jobSampleApp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jobsampleapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jobsampleapp-elasticsearch:9200
    ports:
      - 8080:8080
  jobsampleapp-postgresql:
    extends:
      file: postgresql.yml
      service: jobsampleapp-postgresql
  jobsampleapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jobsampleapp-elasticsearch
